config/routes.rb
Rails.application.routes.draw do
  # require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'
  resources :organizations
  devise_for :users
  devise_scope :users do
    get "sign_out", :to => "devise/sessions#destroy"
  end
  # devise_for :users, controllers: { registrations: 'registrations' }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root 'pages#home'
    resources :users, only: [:show] do
      member do
        post '/verify_phone_number' => 'users#verify_phone_number'
        patch '/update_phone_number' => 'users#update_phone_number'
      end
    end
  
    resources :rooms, except: [:edit] do
      member do
        get 'listing'
        get 'pricing'
        get 'description'
        get 'photo_upload'
        get 'amenities'
        get 'location'
        get 'preload'
        get 'preview'
      end
      resources :photos, only: [:create, :destroy]
      resources :reservations, only: [:create]
      resources :calendars
    end
  
    resources :guest_reviews, only: [:create, :destroy]
    resources :host_reviews, only: [:create, :destroy]
  
    get '/your_trips' => 'reservations#your_trips'
    get '/your_reservations' => 'reservations#your_reservations'
  
    get 'search' => 'pages#search'
    get 'dashboard' => 'dashboards#index'
  
    resources :reservations, only: [:approve, :decline] do
      member do
        post '/approve' => "reservations#approve"
        post '/decline' => "reservations#decline"
      end
    end
  
    resources :revenues, only: [:index]
  
    resources :conversations, only: [:index, :create]  do
      resources :messages, only: [:index, :create]
    end
  
    get '/host_calendar' => "calendars#host"
    get '/payment_method' => "users#payment"
    get '/payout_method' => "users#payout"
    post '/add_card' => "users#add_card"
  
    get '/notification_settings' => 'settings#edit'
    post '/notification_settings' => 'settings#update'
  
    get '/notifications' => 'notifications#index'
  
    mount ActionCable.server => '/cable'
  
  end
  

app/models/room.rb
class Room < ApplicationRecord
  enum instant: {Request: 0, Instant: 1}
    has_many_attached :images
    has_one_attached :cover
  #  searchkick 
    belongs_to :user
    has_many :reservations
    has_many :guest_reviews
    has_many :calendars
    def search_data
      {
        address: address,
        summary: summary,
        price: price,
        listing_name: listing_name
      }
    end
  
    validates :home_type, presence: true
    validates :room_type, presence: true
    validates :accommodate, presence: true
    validates :bed_room, presence: true
    validates :bath_room, presence: true
    
    # geocoded_by :address
    # after_validation :geocode, if: :address_changed?
    
  
    def average_rating
      guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorised, only: [:listing, :pricing, :description, :photo_upload, :amenities, :location, :update]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    # if !current_user.is_active_host
    #   return redirect_to payout_method_path, alert: "Please Connect to Stripe Express first."
    # end

    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saved..."
    else
      flash[:alert] = "Something went wrong..."
      render :new
    end
  end

  def show
    @photos = @room.images
    @guest_reviews = @room.guest_reviews
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @room.photos
  end

  def amenities
  end

  def location
  end

  def update

    new_params = room_params
    new_params = room_params.merge(active: true) if is_ready_room

    if @room.update(new_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end

  # --- Reservations ---
  def preload
    today = Date.today
    reservations = @room.reservations.where("(start_date >= ? OR end_date >= ?) AND status = ?", today, today, 1)
    unavailable_dates = @room.calendars.where("status = ? AND day > ?", 1, today)

    special_dates = @room.calendars.where("status = ? AND day > ? AND price <> ?",0, today, @room.price)

    render json: {
        reservations: reservations,
        unavailable_dates: unavailable_dates,
        special_dates: special_dates
    }
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @room)
    }

    render json: output
  end

  private
    def is_conflict(start_date, end_date, room)
      check = room.reservations.where("(? < start_date AND end_date < ?) AND status = ?", start_date, end_date, 1)
      check_2 = room.calendars.where("day BETWEEN ? AND ? AND status = ?", start_date, end_date, 1).limit(1)

      check.size > 0 || check_2.size > 0 ? true : false
    end

    def set_room
      @room = Room.find(params[:id])
    end

    def is_authorised
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @room.user_id
    end

    def is_ready_room
      !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.address.blank?
    end

    def room_params
      params.require(:room).permit(:home_type, :room_type, :accommodate, :bed_room, :bath_room, :listing_name, :summary,:cover, :images, :latitude, :longitude, :address, :is_tv, :is_kitchen, :is_air, :is_heating, :is_internet, :price, :active, :instant)
    end
end

app/views/rooms/_room_menu.html.erb
<ul class="sidebar-list">
  <li class="sidebar-item">
    <p>Please fill up all the following links forms.</p>

    <%= link_to "Listing", listing_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Pricing", pricing_room_path, class: "sidebar-link active" %>
    <% if !@room.price.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Description", description_room_path, class: "sidebar-link active" %>
    <% if !@room.listing_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Amenities", amenities_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Location", location_room_path, class: "sidebar-link active" %>
    <% if !@room.address.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
</ul>
<hr/>

<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.address.blank? %>

<%= form_for @room do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>

app/views/rooms/_rooms_list.html.erb
<% rooms.each do |room| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading preview">
          <%= image_tag(url_for(room.cover),size:"300x300") %>
        </div>
        <div class="panel-body">
          <%= link_to room.listing_name, room %><br/>
          RM<%= room.price %> - <%= room.home_type %> - <%= pluralize(room.bed_room, "bed") %>
        </div>
      </div>
    </div>
<% end %>

app/views/rooms/amenities.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.check_box :is_tv %> TV
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_kitchen %> Kitchen
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_internet %> Internet
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.check_box :is_heating %> Heating
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_air %> Air Conditioning
                </div>
              </div>
              <br/><br/>

              <div class="row" style="margin-left:3px;">
                <%= f.submit "Save", class: "btn btn-primary" %>
              </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<%# <h1>Room#create</h1>
<p>Find me in app/views/room/create.html.erb</p> %>

app/views/rooms/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
                <label>Listing name</label>
                <%= f.text_field :listing_name, placeholder: "What is your listing name?", class: "form-control", required: true %>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
                <label>Summary</label>
                <%= f.text_area :summary, rows: 5, placeholder: "Summary of your house", class: "form-control", required: true %>
              </div>
            

              <div>
                <%= f.submit "Save", class: "btn btn-primary" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<% if (user_signed_in?) && !current_page?(root_path)%>
    <nav class="navbar navbar-default" style="background-color: #0E1854;">
      <div class="container">
        <ul class="nav navbar-nav">
          <li <% if current_page?(dashboard_path) %> class="active" <% end %> ><%= link_to "Dashboard", dashboard_path %></li>
          <li <% if current_page?(rooms_path) %> class="active" <% end %> ><%= link_to "Manage Listings", rooms_path %></li>
          <li <% if current_page?(conversations_path) %> class="active" <% end %> ><%= link_to "Messages", conversations_path %></li>
        </ul>
      </div>
    </nav>
<% end %>

<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading" style="display:flex; justify-content:center;">  
        Listings
      </div>
      <div class="panel-body">

        <% @rooms.each do |room| %>
          <div class="row">
            <div class="col-md-7">
              <h4><%= room.listing_name %></h4>
            </div>
            <div class="card col-md-11" style="display:flex; justify-content:flex-end;">
              <i class="fas fa-pen-alt"><%= link_to "Update", listing_room_path(room) %></i>
            </div>
          </div>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Home Type</label>
                  <%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                                id: "home_type", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Room Type</label>
                  <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                                id: "room_type", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <%# <div class="col-md-4 select"> %>
                <%# <div class="form-group"> %>
                  <%# <label>Booking Type</label> %>
                  <%# <%= f.select :instant, Room.instants.map {|key,value| [key.humanize, key]}, selected: 'Instant', prompt: "Select...", class: "form-control" %>
                <%# </div> %>
              <%# </div> %>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Accommodate</label>
                  <%= f.select :accommodate, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                id: "accommodate", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Bedrooms</label>
                  <%= f.select :bed_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                id: "bed_room", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Bathrooms</label>
                  <%= f.select :bath_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                id: "bath_rooms", prompt: "Select...", class: "form-control" %>
                </div>
              </div>
            </div>
            <label>Room Cover Photo</label>
              <%= f.file_field :cover %>
            <label>Images</label>
              <%= f.file_field :images, multiple: true %><br>
            <div><%= f.submit "Save", class: "btn btn-primary" %></div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/location.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="container">
          <%= form_for @room, :html => { :id => "form" } do |f| %>

            <div class="row">
              <div class="form-group">
                <label>* Find your location and save it. </label>
                  <%=f.text_field :address, id:"pac-input", placeholder:"Where is your address?", class:"form-control"%>
      </div>

      <div class="form-group">
                <%=f.text_field :latitude, id:"lat", style:"display:none;"%>
      </div>

      <div class="form-group">
                <%=f.text_field :longitude, id:"long", style:"display:none;"%>
      </div>

      <div class="pac-card" id="pac-card">
      <div id="latitude" data-lat= "<%= @room.latitude %>">
        <%# <div id="title">
          Autocomplete search
        </div> %>
        <div id="type-selector" class="pac-controls">
        </div>
        <div id="strict-bounds-selector" class="pac-controls">
        </div>
      </div>
      
    </div>
      <div id="map" ></div>
      </div>
            <div class="row submit-btn" id="longtitude" data-long= "<%= @room.longitude%>">
              <%= f.submit "Save", class: "btn btn-primary" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>





 <script>
      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">
      function initMap() {
        var lt = parseFloat(document.querySelector("#latitude").dataset["lat"])
        var ln = parseFloat(document.querySelector("#longtitude").dataset["long"])
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: lt, lng: ln},
          zoom: 13
        });
        console.log(lt)
                console.log(ln)
        var card = document.getElementById('pac-card');
        var input = document.getElementById('pac-input');
        var types = document.getElementById('type-selector');
        var strictBounds = document.getElementById('strict-bounds-selector');
        map.controls[google.maps.ControlPosition.TOP_RIGHT].push(card);
        var autocomplete = new google.maps.places.Autocomplete(input);
        // Bind the map's bounds (viewport) property to the autocomplete object,
        // so that the autocomplete requests use the current map bounds for the
        // bounds option in the request.
        autocomplete.bindTo('bounds', map);
        // Set the data fields to return when the user selects a place.
        autocomplete.setFields(
            ['address_components', 'geometry', 'icon', 'name']);
        var lt = parseFloat(document.querySelector("#latitude").dataset["lat"])
        var ln = parseFloat(document.querySelector("#longtitude").dataset["long"])
        var infowindow = new google.maps.InfoWindow();
        var infowindowContent = document.getElementById('infowindow-content');
        infowindow.setContent(infowindowContent);
        var marker = new google.maps.Marker({
          map: map,
          anchorPoint: new google.maps.Point(0, -29)
        });
        autocomplete.addListener('place_changed', function() {
          infowindow.close();
          marker.setVisible(false);
          var place = autocomplete.getPlace();
          
          if (!place.geometry) {
            // User entered the name of a Place that was not suggested and
            // pressed the Enter key, or the Place Details request failed.
            window.alert("No details available for input: '" + place.name + "'");
            return;
          }
          document.querySelector("#lat").value = place.geometry.location.lat();
          document.querySelector("#long").value = place.geometry.location.lng();
          var form = document.querySelector("#form");
          form.addEventListener('submit', function() {
          });
          // If the place has a geometry, then present it on a map.
          if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);
          } else {
            map.setCenter(place.geometry.location);
            map.setZoom(17);  // Why 17? Because it looks good.
          }
          marker.setPosition(place.geometry.location);
          marker.setVisible(true);
          
          var address = '';
          if (place.address_components) {
            address = [
              (place.address_components[0] && place.address_components[0].short_name || ''),
              (place.address_components[1] && place.address_components[1].short_name || ''),
              (place.address_components[2] && place.address_components[2].short_name || '')
            ].join(' ');
          }
          infowindowContent.children['place-icon'].src = place.icon;
          infowindowContent.children['place-name'].textContent = place.name;
          infowindowContent.children['place-address'].textContent = address;
          infowindow.open(map, marker);
        });
        // Sets a listener on a radio button to change the filter type on Places
        // Autocomplete.
        function setupClickListener(id, types) {
          var radioButton = document.getElementById(id);
          radioButton.addEventListener('click', function() {
            autocomplete.setTypes(types);
          });
        }
        setupClickListener('changetype-all', []);
        setupClickListener('changetype-address', ['address']);
        setupClickListener('changetype-establishment', ['establishment']);
        setupClickListener('changetype-geocode', ['geocode']);
        document.getElementById('use-strict-bounds')
            .addEventListener('click', function() {
              console.log('Checkbox clicked! New state=' + this.checked);
              autocomplete.setOptions({strictBounds: this.checked});
            });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCLwih_dEjx7rHvO04och6w_zABvfO8Dcw&libraries=places&callback=initMap"
        async defer></script>

app/views/rooms/new.html.erb
<br><div class="panel panel-default">
   <h3> *** Add Your Place To Our Website To Get Guests ***</h3>
  <div class="panel-body"><br><br>
    <div class="container">

      <%= form_for @room do |f| %>

        <div class="row">

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Home Type</label>
              <%= f.select :home_type, [["Apartment", "Apartment"], ["Hotel", "Hotel"], ],
                            id: "home_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Room Type</label>
              <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                            id: "room_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <%# <div class="col-md-4 select"> %>
            <%# <div class="form-group"> %>
              <%# <label>Booking Type</label> %>
              <%# <%= f.select :instant, Room.instants.map {|key,value| [key.humanize, key]}, selected: 'Instant', prompt: "Select...", class: "form-control" %> 
            <%# </div> %>
          <%# </div> %>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Accommodate</label>
              <%= f.select :accommodate, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                            id: "accommodate", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bedrooms</label>
              <%= f.select :bed_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                            id: "bed_room", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bathrooms</label>
              <%= f.select :bath_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                            id: "bath_rooms", prompt: "Select...", class: "form-control" %>
            </div>
          </div>
        </div>
            <label>Room Cover Photo</label>
              <%= f.file_field :cover %>
              <label>Images</label>
              <%= f.file_field :images, multiple: true %><br>
        <div><%= f.submit "Create My Room", class: "btn btn-primary" %></div>

      <% end %>

    </div>
  </div>
</div>

app/views/rooms/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
                <label>Price</label>
                <%= f.text_field :price, placeholder: "eg: 100 (the currency is RM)", class: "form-control", required: true %>
              </div>
            
            <div class="row col-md-3">
              <%= f.submit "Save", class: "btn btn-primary" %>
            </div>
          </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<!-- Image -->
<div class="row">
  <div class="col-md-12">
    <%= image_tag @room.cover, width: "100%" %>
  </div>
</div>
<br/>

<div class="row">

  <!-- LEFT PANEL -->
  <div class="col-md-8">

    <!-- Listing Name -->
    <div class="row">
      <div class="col-md-8">
        <h1><%= @room.listing_name %></h1>
        <%= @room.address %>
      </div>
      <div class="col-md-4 text-center">
        Hosted By (<%= @room.user.fullname %>)
      </div>
    </div>
    <hr/>

    <!-- Room Info -->
    <div class="row text-babu">
      <div class="row text-center row-space-1">
        <div class="col-md-3">
          <i class="fa fa-home fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-user-circle-o fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-bed fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-bath fa-2x"></i>
        </div>
      </div>

      <div class="row text-center">
        <div class="col-md-3"><%= @room.home_type %></div>
        <div class="col-md-3"><%= pluralize(@room.accommodate, "Guest") %></div>
        <div class="col-md-3"><%= pluralize(@room.bed_room, "Bedroom") %></div>
        <div class="col-md-3"><%= pluralize(@room.bath_room, "Bathroom") %></div>
      </div>

    </div>
    <hr/>

    <!-- About -->
    <div class="row">
      <div class="col-md-12">
        <h3>About This Listing</h3>
        <p><%= @room.summary %></p>
      </div>
    </div>
    <hr/>

    <!-- Amenities -->
    <div class="row">
      <div class="col-md-3">
        <h4>Amenities</h4>
      </div>

      <div class="col-md-9">
        <div class="row">
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%= 'text-line-through' if !@room.is_tv %>">TV</li>
              <li class="<%= 'text-line-through' if !@room.is_kitchen %>">Kitchen</li>
              <li class="<%= 'text-line-through' if !@room.is_internet %>">Internet</li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%= 'text-line-through' if !@room.is_heating %>">Heating</li>
              <li class="<%= 'text-line-through' if !@room.is_air %>">Air Conditioning</li>
            </ul>
          </div>

        </div>
      </div>

    </div>
    <hr/>

    <!-- Carousel -->
    <div class="row">

      <% if @photos.length > 0 %>
            <% @photos.each do |photo| %>
                  <%= image_tag(url_for(photo),size:"300x300") %>
            <% end %>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <% end %>
    </div>
    <hr/>
    <!-- REVIEWS -->
    <div class="row" id="longtitude" data-long= "<%= @room.longitude %>">
      <div class="col-md-12">
        <h3>
          <%= pluralize(@guest_reviews.count, "Review") %>
          <span id="average_rating"></span>
        </h3>
        <div class="container">
          <div><%= render "reviews/guest_list" %></div>
        </div>
      </div>
    </div>
    <br/>
    <hr/>

    <!-- GOOGLE MAP -->
    <div class="row" id="latitude" data-lat= "<%= @room.latitude %>">

      <div id="map" style="width: 100%; height: 400px"></div>

     <script> 
  var lt = parseFloat(document.querySelector("#latitude").dataset["lat"])
  var ln = parseFloat(document.querySelector("#longtitude").dataset["long"])
  var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat:lt, lng:ln},
          
          zoom: 8
        });
        var marker = new google.maps.Marker({
          position: {lat:lt, lng:ln},
          map: map,
          title: 'Hello World!'
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCLwih_dEjx7rHvO04och6w_zABvfO8Dcw&callback=initMap"
    async defer></script> 
    </div>
    <hr/>

    <!-- NEAR BY ROOMS -->
    <div class="row">
      <h3>Near by</h3>
      <% for room in @room.nearbys(10) %>
          <div class="col-md-4">
            <div class="panel panel-default">
              <div class="panel-heading preview">
                <%= image_tag url_for(room.cover) %>
              </div>
              <div class="panel-body">
                <%= link_to room.listing_name, room %><br/>
                (<%= room.distance.round(2) %> kms away)
              </div>
            </div>
          </div>
      <% end %>
    </div>

  </div>


  <!-- RIGHT PANEL -->
  <div class="col-md-4">
    <!-- Reservation Form -->
    <%= render 'reservations/form' %>
  </div>
</div>

<script>
$(document).ready(function() {
  $('#average_rating').raty({
    path: '/assets',
    readOnly: true,
    score: <%= @room.average_rating %>
  });
});
</script>

app/views/rooms/update.html.erb
<%# <h1>Room#update</h1>
<p>Find me in app/views/room/update.html.erb</p> %>