config/routes.rb
Rails.application.routes.draw do
  # require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'
  resources :organizations
  devise_for :users
  devise_scope :users do
    get "sign_out", :to => "devise/sessions#destroy"
  end
  # devise_for :users, controllers: { registrations: 'registrations' }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root 'pages#home'
    resources :users, only: [:show] do
      member do
        post '/verify_phone_number' => 'users#verify_phone_number'
        patch '/update_phone_number' => 'users#update_phone_number'
      end
    end
  
    resources :rooms, except: [:edit] do
      member do
        get 'listing'
        get 'pricing'
        get 'description'
        get 'photo_upload'
        get 'amenities'
        get 'location'
        get 'preload'
        get 'preview'
      end
      resources :photos, only: [:create, :destroy]
      resources :reservations, only: [:create]
      resources :calendars
    end
  
    resources :guest_reviews, only: [:create, :destroy]
    resources :host_reviews, only: [:create, :destroy]
  
    get '/your_trips' => 'reservations#your_trips'
    get '/your_reservations' => 'reservations#your_reservations'
  
    get 'search' => 'pages#search'
    get 'dashboard' => 'dashboards#index'
  
    resources :reservations, only: [:approve, :decline] do
      member do
        post '/approve' => "reservations#approve"
        post '/decline' => "reservations#decline"
      end
    end
  
    resources :revenues, only: [:index]
  
    resources :conversations, only: [:index, :create]  do
      resources :messages, only: [:index, :create]
    end
  
    get '/host_calendar' => "calendars#host"
    get '/payment_method' => "users#payment"
    get '/payout_method' => "users#payout"
    post '/add_card' => "users#add_card"
  
    get '/notification_settings' => 'settings#edit'
    post '/notification_settings' => 'settings#update'
  
    get '/notifications' => 'notifications#index'
  
    mount ActionCable.server => '/cable'
  
  end
  

app/models/organization.rb
class Organization < ApplicationRecord
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :email, :number, :address, :service, :about)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= simple_form_for(@organization) do |f|%>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs" id= "form">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :number %>
    <%= f.input :service %>
    <%= f.input :about %>
    <%= f.input :address %>
    <%=f.text_field :latitude, id:"lat", style:"display:none;"%>
    <%=f.text_field :longitude, id:"long", style:"display:none;"%>
  </div>
  <div class="pac-card" id="pac-card">
      <div id="latitude" data-lat= "<%= @organization.latitude %>">
        <div id="title">
        </div>
        <div id="type-selector" class="pac-controls">
        </div>
        <div id="strict-bounds-selector" class="pac-controls">
      </div>
  </div>
    <div id="map" ></div>
      </div>
            <div class="text-center" id="longtitude" data-long= "<%= @organization.longitude%>">
              <%# <%= f.submit "Save", class: "btn btn-form" %> %>
            </div>
        </div>
      </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<script>
      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">
      function initMap() {
        var lt = parseFloat(document.querySelector("#latitude").dataset["lat"])
        var ln = parseFloat(document.querySelector("#longtitude").dataset["long"])
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: lt, lng: ln},
          zoom: 13
        });
        console.log(lt)
                console.log(ln)
        var card = document.getElementById('pac-card');
        var input = document.getElementById('pac-input');
        var types = document.getElementById('type-selector');
        var strictBounds = document.getElementById('strict-bounds-selector');
        map.controls[google.maps.ControlPosition.TOP_RIGHT].push(card);
        var autocomplete = new google.maps.places.Autocomplete(input);
        // Bind the map's bounds (viewport) property to the autocomplete object,
        // so that the autocomplete requests use the current map bounds for the
        // bounds option in the request.
        autocomplete.bindTo('bounds', map);
        // Set the data fields to return when the user selects a place.
        autocomplete.setFields(
            ['address_components', 'geometry', 'icon', 'name']);
        var lt = parseFloat(document.querySelector("#latitude").dataset["lat"])
        var ln = parseFloat(document.querySelector("#longtitude").dataset["long"])
        var infowindow = new google.maps.InfoWindow();
        var infowindowContent = document.getElementById('infowindow-content');
        infowindow.setContent(infowindowContent);
        var marker = new google.maps.Marker({
          map: map,
          anchorPoint: new google.maps.Point(0, -29)
        });
        autocomplete.addListener('place_changed', function() {
          infowindow.close();
          marker.setVisible(false);
          var place = autocomplete.getPlace();
          
          if (!place.geometry) {
            // User entered the name of a Place that was not suggested and
            // pressed the Enter key, or the Place Details request failed.
            window.alert("No details available for input: '" + place.name + "'");
            return;
          }
          document.querySelector("#lat").value = place.geometry.location.lat();
          document.querySelector("#long").value = place.geometry.location.lng();
          var form = document.querySelector("#form");
          form.addEventListener('submit', function() {
          });
          // If the place has a geometry, then present it on a map.
          if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);
          } else {
            map.setCenter(place.geometry.location);
            map.setZoom(17);  // Why 17? Because it looks good.
          }
          marker.setPosition(place.geometry.location);
          marker.setVisible(true);
          
          var address = '';
          if (place.address_components) {
            address = [
              (place.address_components[0] && place.address_components[0].short_name || ''),
              (place.address_components[1] && place.address_components[1].short_name || ''),
              (place.address_components[2] && place.address_components[2].short_name || '')
            ].join(' ');
          }
          infowindowContent.children['place-icon'].src = place.icon;
          infowindowContent.children['place-name'].textContent = place.name;
          infowindowContent.children['place-address'].textContent = address;
          infowindow.open(map, marker);
        });
        // Sets a listener on a radio button to change the filter type on Places
        // Autocomplete.
        function setupClickListener(id, types) {
          var radioButton = document.getElementById(id);
          radioButton.addEventListener('click', function() {
            autocomplete.setTypes(types);
          });
        }
        setupClickListener('changetype-all', []);
        setupClickListener('changetype-address', ['address']);
        setupClickListener('changetype-establishment', ['establishment']);
        setupClickListener('changetype-geocode', ['geocode']);
        document.getElementById('use-strict-bounds')
            .addEventListener('click', function() {
              console.log('Checkbox clicked! New state=' + this.checked);
              autocomplete.setOptions({strictBounds: this.checked});
            });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCLwih_dEjx7rHvO04och6w_zABvfO8Dcw&libraries=places&callback=initMap"
        async defer></script>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Number</th>
      <th>Address</th>
      <th>Service</th>
      <th>About</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.email %></td>
        <td><%= organization.number %></td>
        <td><%= organization.address %></td>
        <td><%= organization.service %></td>
        <td><%= organization.about %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @organization.email %>
</p>

<p>
  <strong>Number:</strong>
  <%= @organization.number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @organization.address %>
</p>

<p>
  <strong>Service:</strong>
  <%= @organization.service %>
</p>

<p>
  <strong>About:</strong>
  <%= @organization.about %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>